apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: hotels.com 
spec:
  ports:
  - port: 6379
    name: redis
    targetPort: 6379
  type: NodePort
  selector:
    name: redis
    app: hotels.com
